### ISSUE TITLE
Optimization Error

### ISSUE THREAD

**Issue by ale18032005** [chan-csu/ADToolbox#16]
ray::_single_cost_ray() (pid=5312, ip=127.0.0.1)
  File "......", line 289, in fetch_and_register_remote_function
    function = pickle.loads(serialized_function)
ModuleNotFoundError: No module named 'adm'

**Comment by ParsaGhadermazi** [comment]
Hi Alejandra,

The problem should be fixed now with this new version. 

Best,
Parsa
